bind_addr = ":8000"
log_level = "debug"

[store]

database_url = "host=localhost dbname=restapi_dev user=postgres password=postgres sslmode=disable"




# Migrate
PGPASSWORD=postgres migrate -path migrations -database "postgres://postgres:postgres@localhost/restapi_dev?sslmode=disable" up